name: FinTrack CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build UserService
        run: mvn -B clean install --file user-service/user-service/pom.xml
      - name: Build NotificationService
        run: mvn -B clean install --file notification-service/notification-service/pom.xml
      - name: Build AnalyticsService
        run: mvn -B clean install --file analytics-service/analytics-service/pom.xml

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Build Frontend
        run: |
          cd frontend-app/fintrack-ui
          npm install
          npm run build
